# tasks file for roles/nginx
- name: Copying certificates and keys
  copy:
    src: files/"{{ item }}"
    dest: /etc/nginx/certs/
    owner: root
    group: root
    mode: '0644'
  with_items:
    - nginx-selfsigned.crt
    - nginx-selfsigned.key

- name: Copying rules file 
  copy:
    src: templates/nginx.conf.j2 
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0755'
  notify:
   - nginxrestart
